import type { Member, Event, Subscription } from './types';

export const members: Member[] = [
  {
    id: '1',
    fullName: 'John Doe',
    email: 'john.doe@example.com',
    phoneNumber: '123-456-7890',
    address: '123 Main St, Anytown, USA',
    membershipStartDate: '2020-01-15',
    membershipType: 'Regular',
    status: 'Active',
    profilePhotoUrl: 'https://placehold.co/100x100.png',
    outstandingDues: 0,
  },
  {
    id: '2',
    fullName: 'Jane Smith',
    email: 'jane.smith@example.com',
    phoneNumber: '987-654-3210',
    address: '456 Oak Ave, Anytown, USA',
    membershipStartDate: '2018-03-22',
    membershipType: 'Lifetime',
    status: 'Active',
    outstandingDues: 0,
  },
  {
    id: '3',
    fullName: 'Peter Jones',
    email: 'peter.jones@example.com',
    phoneNumber: '555-123-4567',
    address: '789 Pine Ln, Anytown, USA',
    membershipStartDate: '2022-07-10',
    membershipType: 'Regular',
    status: 'Inactive',
    outstandingDues: 150,
  },
  {
    id: '4',
    fullName: 'Mary Johnson',
    email: 'mary.johnson@example.com',
    phoneNumber: '555-987-6543',
    address: '101 Maple Dr, Anytown, USA',
    membershipStartDate: '2015-11-05',
    membershipType: 'Honorary',
    status: 'Active',
    outstandingDues: 0,
  },
  {
    id: '5',
    fullName: 'David Williams',
    email: 'david.williams@example.com',
    phoneNumber: '555-555-5555',
    address: '212 Birch Rd, Anytown, USA',
    membershipStartDate: '2023-02-28',
    membershipType: 'Regular',
    status: 'Active',
    outstandingDues: 50,
  },
];

export const events: Event[] = [
  {
    id: 'e1',
    name: 'Annual Charity Gala',
    date: '2024-10-26',
    time: '18:00',
    venue: 'Grand Hotel Ballroom',
    description: 'Our biggest fundraising event of the year.',
    eventType: 'Fundraiser',
    status: 'Upcoming',
  },
  {
    id: 'e2',
    name: 'Community Park Cleanup',
    date: '2024-09-14',
    time: '09:00',
    venue: 'Central Park',
    description: 'Join us to help clean and beautify our local park.',
    eventType: 'Community',
    status: 'Upcoming',
  },
  {
    id: 'e3',
    name: 'Monthly Members Meeting',
    date: '2024-08-05',
    time: '19:00',
    venue: 'Clubhouse',
    description: 'Regular monthly meeting for all members.',
    eventType: 'Meeting',
    status: 'Upcoming',
  },
  {
    id: 'e4',
    name: 'Summer Picnic',
    date: '2024-07-20',
    time: '12:00',
    venue: 'Lakeview Park',
    description: 'A fun social event for members and their families.',
    eventType: 'Social',
    status: 'Completed',
  },
  {
    id: 'e5',
    name: 'Blood Donation Drive',
    date: '2024-06-15',
    time: '10:00',
    venue: 'Community Center',
    description: 'Partnering with the Red Cross to save lives.',
    eventType: 'Community',
    status: 'Completed',
  },
  {
    id: 'e6',
    name: 'Holiday Toy Drive',
    date: '2023-12-01',
    time: '09:00',
    venue: 'Town Hall',
    description: 'Canceled due to unforeseen circumstances.',
    eventType: 'Community',
    status: 'Canceled',
  }
];

export const subscriptions: Subscription[] = [
  {
    id: 's1',
    memberId: '1',
    memberName: 'John Doe',
    paymentDate: '2024-01-20',
    amount: 150,
    paymentMethod: 'Online',
    status: 'Paid',
    notes: 'Annual Dues 2024',
  },
  {
    id: 's2',
    memberId: '2',
    memberName: 'Jane Smith',
    paymentDate: '2024-01-10',
    amount: 0,
    paymentMethod: 'Online',
    status: 'Paid',
    notes: 'Lifetime Member - No Dues',
  },
  {
    id: 's3',
    memberId: '3',
    memberName: 'Peter Jones',
    paymentDate: '2024-01-15',
    amount: 150,
    paymentMethod: 'Online',
    status: 'Unpaid',
    notes: 'Annual Dues 2024',
  },
  {
    id: 's4',
    memberId: '5',
    memberName: 'David Williams',
    paymentDate: '2024-02-01',
    amount: 100,
    paymentMethod: 'Cash',
    status: 'Partial',
    notes: 'Partial payment for 2024 dues.',
  },
    {
    id: 's5',
    memberId: '1',
    memberName: 'John Doe',
    paymentDate: '2023-01-18',
    amount: 150,
    paymentMethod: 'Bank Transfer',
    status: 'Paid',
    notes: 'Annual Dues 2023',
  },
];
